Consider the below code to answer further questions:


import numpy as np

list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]

array_list = np.array(object = list_)

#### Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

Yes, there is a difference in the data type of the "list_" variable and the "array_list" variable. The "list_" variable is a Python list, whereas the "array_list" variable is a NumPy array.

To print the data types of both variables, we can use the type() function in Python, as follows:

In [2]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(type(list_))
print(type(array_list))


<class 'list'>
<class 'numpy.ndarray'>


#### Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

To print the data type of each and every element of the "list_" variable, we can use a for loop to iterate over the elements of the list and print the data type of each element using the type() function, as follows:

In [3]:
list_ = ['1', '2', '3', '4', '5']

for elem in list_:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


As we can see, each element of the "list_" variable is a string.

To print the data type of each and every element of the "array_list" variable, we can use the dtype attribute of the NumPy array, as follows:

In [4]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

print(array_list.dtype)

#As we can see, the data type of each element of the "array_list" variable is a Unicode string of length 1 (i.e., each element is a single character string).

<U1


Q3. Considering the following changes in the variable, array_list:

array_list = np.array(object = list_, dtype = int)

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

Consider the below code to answer further questions:

import numpy as np

num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

num_array = np.array(object = num_list)

Yes, there will be a difference in the data type of the elements present in both the variables "list_" and "array_list" after making the change:

In [5]:
array_list = np.array(object=list_, dtype=int)


In this line of code, we are explicitly specifying the data type of the NumPy array as "int" using the "dtype" parameter. Therefore, each element of the NumPy array will be converted to an integer.

To print the data types of each and every element present in both the variables "list_" and "array_list", we can use the same approach as before, i.e., using a for loop to iterate over the elements of the list and print the data type of each element using the type() function:

In [6]:
list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

for elem in list_:
    print(type(elem))
    
for elem in array_list:
    print(type(elem))


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


As we can see, each element of the original "list_" variable is a string, while each element of the modified "array_list" variable is an integer.

Regarding the second code snippet, the code creates a NumPy array called "num_array" by converting a Python list called "num_list" to a NumPy array. The "num_list" variable contains a list of lists, which represents a 2-dimensional array. The NumPy array is created using the np.array() function from the NumPy library, and the Python list is passed as the input argument to this function using the "object" parameter.

#### Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [7]:
import numpy as np

num_list = [[1, 2, 3], [4, 5, 6]]
num_array = np.array(object=num_list)

print("Shape of num_array:", num_array.shape)
print("Size of num_array:", num_array.size)



Shape of num_array: (2, 3)
Size of num_array: 6


As we can see, the shape of the "num_array" variable is a tuple (2, 3), which indicates that it has 2 rows and 3 columns. The size of the "num_array" variable is 6, which is the total number of elements in the array.

#### Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [8]:
import numpy as np

zeros_array = np.zeros((3,3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


#### Q6. Create an identity matrix of shape (5,5) using numpy functions?

[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]